---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "${SERVICE_NAME}"
    namespace: "${NAMESPACE}"
  spec:
    ports:
    - name: "http"
      port: ${INTERNAL_PORT}
      targetPort: ${INTERNAL_PORT}
    selector:
      deploymentconfig: "${SERVICE_NAME}"
    type: "ClusterIP"
- apiVersion: "apps.openshift.io/v1"
  kind: "DeploymentConfig"
  metadata:
    name: "${SERVICE_NAME}"
    namespace: "${NAMESPACE}"
  spec:
    replicas: 1
    selector:
      deploymentconfig: "${SERVICE_NAME}"
    template:
      metadata:
        labels:
          deploymentconfig: "${SERVICE_NAME}"
        namespace: "${NAMESPACE}"
      spec:
        containers:
        - image: "${IMAGE}"
          imagePullPolicy: "IfNotPresent"
          name: "${SERVICE_NAME}"
          ports:
          - containerPort: ${INTERNAL_PORT}
            name: "http"
            protocol: "TCP"
      