apiVersion: v1
kind: List
items:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: '${SERVICE_NAME}'
    spec:
      selector:
        app: '${SERVICE_NAME}'
      serviceName: '${SERVICE_NAME}'
      replicas: 1
      template:
        metadata:
          labels:
            app: '${SERVICE_NAME}'
        spec:
          containers:
            - image: '${IMAGE}'
              name: '${SERVICE_NAME}'
              ports:
                - containerPort: 5775
                  protocol: UDP
                - containerPort: 6831
                  protocol: UDP
                - containerPort: 6832
                  protocol: UDP
                - containerPort: 5778
                  protocol: TCP
                - containerPort: ${TRACE_PORT}
                  protocol: TCP
                - containerPort: ${INTERNAL_PORT}
                  protocol: TCP
                - containerPort: 9411
                  protocol: TCP
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: '${SERVICE_NAME}-query'
      labels:
        app: '${SERVICE_NAME}'
    spec:
      ports:
        - name: query-http
          port: ${TRACE_PORT}
          protocol: TCP
          targetPort: ${TRACE_PORT}
      selector:
        app: '${SERVICE_NAME}'
  - apiVersion: v1
    kind: Service
    metadata:
      name: '${SERVICE_NAME}-rest'
      labels:
        app: '${SERVICE_NAME}'
    spec:
      ports:
        - name: '${SERVICE_NAME}-rest'
          port: ${INTERNAL_PORT}
          protocol: TCP
          targetPort: ${INTERNAL_PORT}
      selector:
        app: '${SERVICE_NAME}'
